/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package validationapi;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author esmer
 */
public class AnimalSelectUK extends javax.swing.JDialog {

    
    FondoPanel fondo = new FondoPanel();
    /**
     * Creates new form AnimalSelect
     */
    public AnimalSelectUK(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        this.setContentPane(fondo);
        
        initComponents();
        
        setSize(428, 826);
        
        Color c=new Color(1f,1f,1f,.0f );
        
        lionbtn.setBorder(BorderFactory.createEmptyBorder());
        lionbtn.setContentAreaFilled(false);
        lionbtn.setBackground(c);
        lionbtn.setFocusPainted(false);
        
        koalabtn.setBorder(BorderFactory.createEmptyBorder());
        koalabtn.setContentAreaFilled(false);
        koalabtn.setBackground(c);
        koalabtn.setFocusPainted(false);
        
        giraffebtn.setBorder(BorderFactory.createEmptyBorder());
        giraffebtn.setContentAreaFilled(false);
        giraffebtn.setBackground(c);
        giraffebtn.setFocusPainted(false);
        
        tigerbtn.setBorder(BorderFactory.createEmptyBorder());
        tigerbtn.setContentAreaFilled(false);
        tigerbtn.setBackground(c);
        tigerbtn.setFocusPainted(false);
        
        elephantbtn.setBorder(BorderFactory.createEmptyBorder());
        elephantbtn.setContentAreaFilled(false);
        elephantbtn.setBackground(c);
        elephantbtn.setFocusPainted(false);
        
        
        panelTransparente.setBackground(c);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTransparente = new javax.swing.JPanel();
        lionbtn = new javax.swing.JButton();
        koalabtn = new javax.swing.JButton();
        giraffebtn = new javax.swing.JButton();
        tigerbtn = new javax.swing.JButton();
        elephantbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelTransparente.setBackground(new java.awt.Color(255, 255, 255));
        panelTransparente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lionbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lion.png"))); // NOI18N
        lionbtn.setText(org.openide.util.NbBundle.getMessage(AnimalSelectUK.class, "AnimalSelectUK.lionbtn.text")); // NOI18N
        lionbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lionbtnActionPerformed(evt);
            }
        });
        panelTransparente.add(lionbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 143, -1, -1));

        koalabtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/koala.png"))); // NOI18N
        koalabtn.setText(org.openide.util.NbBundle.getMessage(AnimalSelectUK.class, "AnimalSelectUK.koalabtn.text")); // NOI18N
        koalabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                koalabtnActionPerformed(evt);
            }
        });
        panelTransparente.add(koalabtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 133, -1, -1));

        giraffebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/giraffe2.png"))); // NOI18N
        giraffebtn.setText(org.openide.util.NbBundle.getMessage(AnimalSelectUK.class, "AnimalSelectUK.giraffebtn.text")); // NOI18N
        giraffebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giraffebtnActionPerformed(evt);
            }
        });
        panelTransparente.add(giraffebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        tigerbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tiger.png"))); // NOI18N
        tigerbtn.setText(org.openide.util.NbBundle.getMessage(AnimalSelectUK.class, "AnimalSelectUK.tigerbtn.text")); // NOI18N
        tigerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tigerbtnActionPerformed(evt);
            }
        });
        panelTransparente.add(tigerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, -1, -1));

        elephantbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/elephant.png"))); // NOI18N
        elephantbtn.setText(org.openide.util.NbBundle.getMessage(AnimalSelectUK.class, "AnimalSelectUK.elephantbtn.text")); // NOI18N
        elephantbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elephantbtnActionPerformed(evt);
            }
        });
        panelTransparente.add(elephantbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrowBack.png"))); // NOI18N
        jButton1.setText(org.openide.util.NbBundle.getMessage(AnimalSelectUK.class, "AnimalSelectUK.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelTransparente.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTransparente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTransparente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void koalabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_koalabtnActionPerformed
      ReproducirSonido("src/sound/Koala.wav");
        
       koalaUK dialog = new koalaUK(new javax.swing.JFrame(), true);
       dialog.setVisible(true);
    }//GEN-LAST:event_koalabtnActionPerformed

    private void lionbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lionbtnActionPerformed
        ReproducirSonido("src/sound/LionRoar.wav");
        
        LionUK dialog = new LionUK(new javax.swing.JFrame(), true);
        
        dialog.setVisible(true);
    }//GEN-LAST:event_lionbtnActionPerformed

    private void giraffebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giraffebtnActionPerformed
        ReproducirSonido("src/sound/jirafa.wav");
        
        GiraffeUK dialog = new GiraffeUK(new javax.swing.JFrame(), true);
        
        dialog.setVisible(true);
    }//GEN-LAST:event_giraffebtnActionPerformed

    private void tigerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tigerbtnActionPerformed
        ReproducirSonido("src/sound/Tiger.wav");
        
        TigerUK dialog = new TigerUK(new javax.swing.JFrame(), true);
        
        dialog.setVisible(true);
    }//GEN-LAST:event_tigerbtnActionPerformed

    private void elephantbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elephantbtnActionPerformed
        ReproducirSonido("src/sound/Elephant.wav");
        
        ElephantUK dialog = new ElephantUK(new javax.swing.JFrame(), true);
        
        dialog.setVisible(true);
    }//GEN-LAST:event_elephantbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LanguagePage dialog = new LanguagePage(new javax.swing.JFrame(), true);
        
        this.setVisible(false);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnimalSelectUK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnimalSelectUK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnimalSelectUK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnimalSelectUK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AnimalSelectUK dialog = new AnimalSelectUK(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    class FondoPanel extends JPanel{
        private Image img;
        
        @Override
        public void paint(Graphics g){
            img = new ImageIcon(getClass().getResource("/img/Game.png")).getImage();
            
            g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            
            super.paint(g);
        }
    }
    
    public void ReproducirSonido(String nombreSonido){
       try {
        AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File(nombreSonido).getAbsoluteFile());
        Clip clip = AudioSystem.getClip();
        clip.open(audioInputStream);
        clip.start();
       } catch(UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
         System.out.println("Error al reproducir el sonido.");
       }
     }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton elephantbtn;
    private javax.swing.JButton giraffebtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton koalabtn;
    private javax.swing.JButton lionbtn;
    private javax.swing.JPanel panelTransparente;
    private javax.swing.JButton tigerbtn;
    // End of variables declaration//GEN-END:variables
}
