/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package validationapi;

import java.awt.Color;
import java.awt.Font;
import static java.awt.Font.BOLD;
import java.awt.Image;
import java.awt.ItemSelectable;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author esmer
 */
public class LanguagePage extends javax.swing.JDialog {

    /**
     * Creates new form LanguagePage
     */
    public LanguagePage(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(428, 826);
        
        Color c=new Color(1f,1f,1f,.0f ); 
        
        SpainBtn.setBorder(BorderFactory.createEmptyBorder());
        SpainBtn.setContentAreaFilled(false);
        SpainBtn.setBackground(c);
        SpainBtn.setFocusPainted(false);
        
        // Spain Flag
        ImageIcon img1 = new ImageIcon(getClass().getResource("/img/spain.png"));
        Icon spain = new ImageIcon(img1.getImage().getScaledInstance(SpainBtn.getWidth(), SpainBtn.getHeight(), Image.SCALE_DEFAULT));
        SpainBtn.setIcon(spain);
        
        // French Flag
        ImageIcon img2 = new ImageIcon(getClass().getResource("/img/french.png"));
        Icon french = new ImageIcon(img2.getImage().getScaledInstance(FrenchBtn.getWidth(), FrenchBtn.getHeight(), Image.SCALE_DEFAULT));
        FrenchBtn.setIcon(french);
        
        FrenchBtn.setBorder(BorderFactory.createEmptyBorder());
        FrenchBtn.setContentAreaFilled(false);
        FrenchBtn.setBackground(c);
        FrenchBtn.setFocusPainted(false);
        
        // German Flag
        ImageIcon img3 = new ImageIcon(getClass().getResource("/img/german.png"));
        Icon german = new ImageIcon(img3.getImage().getScaledInstance(GermanBtn.getWidth(), GermanBtn.getHeight(), Image.SCALE_DEFAULT));
        GermanBtn.setIcon(german);
        
        GermanBtn.setBorder(BorderFactory.createEmptyBorder());
        GermanBtn.setContentAreaFilled(false);
        GermanBtn.setBackground(c);
        GermanBtn.setFocusPainted(false);
        
        // British Flag
        ImageIcon img4 = new ImageIcon(getClass().getResource("/img/british.png"));
        Icon british = new ImageIcon(img4.getImage().getScaledInstance(BritishBtn.getWidth(), BritishBtn.getHeight(), Image.SCALE_DEFAULT));
        BritishBtn.setIcon(british);
        
        BritishBtn.setBorder(BorderFactory.createEmptyBorder());
        BritishBtn.setContentAreaFilled(false);
        BritishBtn.setBackground(c);
        BritishBtn.setFocusPainted(false);
        
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        SpainBtn = new javax.swing.JButton();
        FrenchBtn = new javax.swing.JButton();
        GermanBtn = new javax.swing.JButton();
        BritishBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        listCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(236, 200, 99));

        jPanel2.setBackground(new java.awt.Color(236, 200, 99));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(101, 34, 38));
        jLabel1.setText(org.openide.util.NbBundle.getMessage(LanguagePage.class, "LanguagePage.jLabel1.text")); // NOI18N
        jPanel2.add(jLabel1);

        jPanel3.setBackground(new java.awt.Color(236, 200, 99));
        jPanel3.setLayout(new java.awt.GridLayout(4, 0, 0, 20));

        SpainBtn.setBackground(new java.awt.Color(236, 200, 99));
        SpainBtn.setText(org.openide.util.NbBundle.getMessage(LanguagePage.class, "LanguagePage.SpainBtn.text")); // NOI18N
        SpainBtn.setBorder(null);
        SpainBtn.setBorderPainted(false);
        SpainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpainBtnActionPerformed(evt);
            }
        });
        jPanel3.add(SpainBtn);

        FrenchBtn.setBackground(new java.awt.Color(236, 200, 99));
        FrenchBtn.setText(org.openide.util.NbBundle.getMessage(LanguagePage.class, "LanguagePage.FrenchBtn.text")); // NOI18N
        FrenchBtn.setBorderPainted(false);
        FrenchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrenchBtnActionPerformed(evt);
            }
        });
        jPanel3.add(FrenchBtn);

        GermanBtn.setBackground(new java.awt.Color(236, 200, 99));
        GermanBtn.setText(org.openide.util.NbBundle.getMessage(LanguagePage.class, "LanguagePage.GermanBtn.text")); // NOI18N
        GermanBtn.setBorderPainted(false);
        GermanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GermanBtnActionPerformed(evt);
            }
        });
        jPanel3.add(GermanBtn);

        BritishBtn.setBackground(new java.awt.Color(236, 200, 99));
        BritishBtn.setText(org.openide.util.NbBundle.getMessage(LanguagePage.class, "LanguagePage.BritishBtn.text")); // NOI18N
        BritishBtn.setBorderPainted(false);
        BritishBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BritishBtnActionPerformed(evt);
            }
        });
        jPanel3.add(BritishBtn);

        jPanel4.setBackground(new java.awt.Color(236, 200, 99));

        listCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ThemeOne", "ThemeTwo", "ThemeThree", "ThemeFour" }));
        listCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listComboActionPerformed(evt);
            }
        });
        jPanel4.add(listCombo);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(108, 108, 108))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SpainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpainBtnActionPerformed
        AnimalSelect dialog = new AnimalSelect(new javax.swing.JFrame(), true);
        this.setVisible(false);
        dialog.setVisible(true);
    }//GEN-LAST:event_SpainBtnActionPerformed

    private void FrenchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrenchBtnActionPerformed
        AnimalSelectFR dialog = new AnimalSelectFR(new javax.swing.JFrame(), true);
        this.setVisible(false);
        dialog.setVisible(true);
    }//GEN-LAST:event_FrenchBtnActionPerformed

    private void GermanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GermanBtnActionPerformed
        AnimalSelectGER dialog = new AnimalSelectGER(new javax.swing.JFrame(), true);
        this.setVisible(false);
        dialog.setVisible(true);
    }//GEN-LAST:event_GermanBtnActionPerformed

    private void BritishBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BritishBtnActionPerformed
        AnimalSelectGER dialog = new AnimalSelectGER(new javax.swing.JFrame(), true);
        this.setVisible(false);
        dialog.setVisible(true);
    }//GEN-LAST:event_BritishBtnActionPerformed

    private void listComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listComboActionPerformed
        
        int seleccion = listCombo.getSelectedIndex();
        try {

            // Dependiendo del click que hagamos, va a coger una opción u otra, para ello usamos un switch
            switch (seleccion) {

                case 0:

                // Creación de unobjeto de la clase Font
                Font f = new Font("Sitka Banner", BOLD, 32);

                // Con la clase UIManager, y el método setLookAndFeel, vamos a cambiar la fuente que ha sido importada y
                // añadida a la librería previamente
                UIManager.setLookAndFeel("com.jtattoo.plaf.bernstein.BernsteinLookAndFeel");

                // Y con la clase SwingUtitlites y el método updateComponentTreeUI, vamos a actualizar y aplicar el tema
                // previamente importada
                SwingUtilities.updateComponentTreeUI(this);
                jLabel1.setFont(f);

                break;

                case 1:

                // Creación de unobjeto de la clase Font
                Font f1 = new Font("Sikta Display", BOLD, 24);

                // Con la clase UIManager, y el método setLookAndFeel, vamos a cambiar la fuente que ha sido importada y
                // añadida a la librería previamente
                UIManager.setLookAndFeel("com.jtattoo.plaf.aero.AeroLookAndFeel");

                // Y con la clase SwingUtitlites y el método updateComponentTreeUI, vamos a actualizar y aplicar el tema
                // previamente importada
                SwingUtilities.updateComponentTreeUI(this);
                jLabel1.setFont(f1);

                break;

                case 2:

                // Creación de unobjeto de la clase Font
                Font f2 = new Font("Sikta Heading", BOLD, 32);

                // Con la clase UIManager, y el método setLookAndFeel, vamos a cambiar la fuente que ha sido importada y
                // añadida a la librería previamente
                UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");

                // Y con la clase SwingUtitlites y el método updateComponentTreeUI, vamos a actualizar y aplicar el tema
                // previamente importada
                SwingUtilities.updateComponentTreeUI(this);
                jLabel1.setFont(f2);

                break;

                case 3:

                // Creación de unobjeto de la clase Font
                Font f3 = new Font("SimSun", BOLD, 32);

                // Con la clase UIManager, y el método setLookAndFeel, vamos a cambiar la fuente que ha sido importada y
                // añadida a la librería previamente
                UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");

                // Y con la clase SwingUtitlites y el método updateComponentTreeUI, vamos a actualizar y aplicar el tema
                // previamente importada
                SwingUtilities.updateComponentTreeUI(this);

                jLabel1.setFont(f3);

                break;

                case 4:

                // Creación de unobjeto de la clase Font
                Font f4 = new Font("Showcard Gotic", BOLD, 32);

                // Con la clase UIManager, y el método setLookAndFeel, vamos a cambiar la fuente que ha sido importada y
                // añadida a la librería previamente
                UIManager.setLookAndFeel("com.jtattoo.plaf.mcwin.McWinLookAndFeel");

                // Y con la clase SwingUtitlites y el método updateComponentTreeUI, vamos a actualizar y aplicar el tema
                // previamente importada
                SwingUtilities.updateComponentTreeUI(this);

                jLabel1.setFont(f4);

                break;

            }
        } catch (Exception e) {

        }
        
    }//GEN-LAST:event_listComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LanguagePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LanguagePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LanguagePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LanguagePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LanguagePage dialog = new LanguagePage(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BritishBtn;
    private javax.swing.JButton FrenchBtn;
    private javax.swing.JButton GermanBtn;
    private javax.swing.JButton SpainBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JComboBox<String> listCombo;
    // End of variables declaration//GEN-END:variables
}
