/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package validationapi;

import org.netbeans.validation.api.builtin.stringvalidation.StringValidators;
import org.netbeans.validation.api.builtin.stringvalidation.Validation_es;
import org.netbeans.validation.api.ui.ValidationGroup;

/**
 *
 * @author esmer
 */
public class LoginPage extends javax.swing.JDialog {

    /**
     * Creates new form LoginPage
     */
    public LoginPage(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(428, 826);
        
        ValidationGroup group = validationPanel1.getValidationGroup();
       
        group.add(usernameTF, new Validation_es());
        group.add(emailTF, StringValidators.EMAIL_ADDRESS);
        group.add(Password, new Validation_es());
        
    }

    LoginPage() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Username = new javax.swing.JLabel();
        usernameTF = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        PassWord = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        login = new javax.swing.JButton();
        validationPanel1 = new org.netbeans.validation.api.ui.swing.ValidationPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(236, 200, 99));

        jPanel2.setBackground(new java.awt.Color(236, 200, 99));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(101, 34, 38));
        jLabel1.setText(org.openide.util.NbBundle.getMessage(LoginPage.class, "LoginPage.jLabel1.text")); // NOI18N
        jPanel2.add(jLabel1);

        jPanel3.setBackground(new java.awt.Color(236, 200, 99));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Username.setBackground(new java.awt.Color(101, 34, 38));
        Username.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Username.setForeground(new java.awt.Color(101, 34, 38));
        Username.setText(org.openide.util.NbBundle.getMessage(LoginPage.class, "LoginPage.Username.text")); // NOI18N
        jPanel3.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        usernameTF.setText(org.openide.util.NbBundle.getMessage(LoginPage.class, "LoginPage.usernameTF.text")); // NOI18N
        jPanel3.add(usernameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 170, 30));

        Email.setBackground(new java.awt.Color(255, 86, 94));
        Email.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Email.setForeground(new java.awt.Color(101, 34, 38));
        Email.setText(org.openide.util.NbBundle.getMessage(LoginPage.class, "LoginPage.Email.text")); // NOI18N
        jPanel3.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        emailTF.setText(org.openide.util.NbBundle.getMessage(LoginPage.class, "LoginPage.emailTF.text")); // NOI18N
        jPanel3.add(emailTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 170, 30));

        PassWord.setBackground(new java.awt.Color(255, 86, 94));
        PassWord.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        PassWord.setForeground(new java.awt.Color(101, 34, 38));
        PassWord.setText(org.openide.util.NbBundle.getMessage(LoginPage.class, "LoginPage.PassWord.text")); // NOI18N
        jPanel3.add(PassWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        Password.setText(org.openide.util.NbBundle.getMessage(LoginPage.class, "LoginPage.Password.text")); // NOI18N
        jPanel3.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 170, 30));

        jPanel4.setBackground(new java.awt.Color(236, 200, 99));
        jPanel4.setLayout(new java.awt.GridLayout(2, 0, 0, 20));

        login.setBackground(new java.awt.Color(101, 34, 38));
        login.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText(org.openide.util.NbBundle.getMessage(LoginPage.class, "LoginPage.login.text")); // NOI18N
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel4.add(login);

        validationPanel1.setBackground(new java.awt.Color(236, 200, 99));
        validationPanel1.setForeground(new java.awt.Color(101, 34, 38));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(validationPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(validationPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        LanguagePage dialog = new LanguagePage(new javax.swing.JFrame(), true);
        this.setVisible(false);
        dialog.setVisible(true);
    }//GEN-LAST:event_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginPage dialog = new LoginPage(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Email;
    private javax.swing.JLabel PassWord;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel Username;
    private javax.swing.JTextField emailTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton login;
    private javax.swing.JTextField usernameTF;
    private org.netbeans.validation.api.ui.swing.ValidationPanel validationPanel1;
    // End of variables declaration//GEN-END:variables
}
